---

- name: Check for brewed apps
  shell: brew list | grep {{ item }}
  register: installed_cliapplications
  with_items: cliapps.brew
  ignore_errors: true
  when: 0 > 1
  tags: osxbrew

- name: Install apps with brew
  homebrew: name={{ item }} state=present
  with_items: cliapps.brew
  tags: osxbrew
