---

# https://gist.github.com/saetia/1623487
# https://github.com/sbecker/dotfiles

- name: register variable for home directory
  command: pwd
  register: homedir
  sudo: no
  tags: osxdefaults

#- name: mac-default | set LANG for better ssh sessions
  # export LANG=en_US.UTF-8, http://www.chrisk.de/blog/2011/07/how-to-fix-ssh-utf-8-issues-in-mac-os-x-lion
  # tags: osxdefaults

- name: Disable resume in Preview
  command: defaults write com.apple.Preview NSQuitAlwaysKeepsWindows -bool false
  notify: restart finder
  tags: osxdefaults

- name: Disable resume in QuickTime Player X
  command: defaults write com.apple.QuickTimePlayerX NSQuitAlwaysKeepsWindows -bool false
  notify: restart finder
  tags: osxdefaults

# Run this once when setting up a new mac!
# Grabbed from https://raw.github.com/pfhayes/dotfiles/master/.osx

- name: Show remaining battery time
  command: defaults write com.apple.menuextra.battery ShowPercent -string "NO"
  notify: restart finder
  when: 0 > 1
  tags: osxdefaults

- name: Hide battery percentage
  command: defaults write com.apple.menuextra.battery ShowTime -string "YES"
  notify: restart finder
  when: 0 > 1
  tags: osxdefaults

- name: Show all filename extensions in Finder
  command: defaults write NSGlobalDomain AppleShowAllExtensions -bool true
  notify: restart finder
  when: 0 > 1
  tags: osxdefaults

- name: Disable the warning when changing a file extension
  command: defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
  notify: restart finder
  tags: osxdefaults

- name: Expand save panels by default
  command: defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
  notify: restart finder
  tags: osxdefaults

- name: Expand print panels by default
  command: defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
  notify: restart finder
  tags: osxdefaults

- name: Disable the Are you sure you want to open this application? dialog
  command: defaults write com.apple.LaunchServices LSQuarantine -bool false
  notify: restart finder
  tags: osxdefaults

- name: Disable shadow in screenshots
  command: defaults write com.apple.screencapture disable-shadow -bool true
  notify: restart finder
  tags: osxdefaults

- name: Disable GateKeeper
  command: spctl --master-disable
  sudo: yes
  tags: osxdefaults

- name: Disable press-and-hold for keys in favor of key repeat
  command: defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
  notify: restart finder
  tags: osxdefaults

- name: Set a blazingly fast keyboard repeat rate
  command: defaults write NSGlobalDomain KeyRepeat -int 1
  notify: restart finder
  tags: osxdefaults

- name: Disable auto-correct
  command: defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
  notify: restart finder
  tags: osxdefaults

- name: Display full POSIX path as Finder window title
  command: defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
  notify: restart finder
  tags: osxdefaults

- name: Enable the 2D Dock
  command: defaults write com.apple.dock no-glass -bool true
  notify: restart finder
  #when: 0 > 1
  tags: osxdefaults

- name: Autohide dock
  command: defaults write com.apple.dock autohide -bool true
  notify: restart finder
  #when: 0 > 1
  tags: osxdefaults

- name: Disable window animations
  command: defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false
  notify: restart finder
  when: 0 > 1
  tags: osxdefaults

- name: Avoid creating .DS_Store files on network volumes
  command: defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
  notify: restart finder
  tags: osxdefaults

- name: Show item info below desktop icons
  command: /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" {{ home }}/Library/Preferences/com.apple.finder.plist
  tags: osxdefaults

- name: Enable snap-to-grid for desktop icons
  command: /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" {{ home }}/Library/Preferences/com.apple.finder.plist
  tags: osxdefaults

- name: Enable tap to click (Trackpad)
  command: defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
  notify: restart finder
  tags: osxdefaults

- name: Enable tap to click (Trackpad) on login screen
  shell: defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 2 && defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
  tags: osxdefaults

- name: Disable "natural" (Lion-style) scrolling
  command: defaults write NSGlobalDomain com.apple.swipescrolldirection -bool true
  tags: osxdefaults

- name: Show the ~/Library folder
  command: chflags nohidden {{ home }}/Library
  sudo: no
  tags: osxdefaults

- name: Use current directory as default search scope in Finder
  command: defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
  notify: restart finder
  tags: osxdefaults

- name: Show Path bar in Finder
  command: defaults write com.apple.finder ShowPathbar -bool true
  notify: restart finder
  tags: osxdefaults

- name: Show Status bar in Finder
  command: defaults write com.apple.finder ShowStatusBar -bool true
  notify: restart finder
  tags: osxdefaults

- name: Do not show Dashboard as a Space
  command: defaults write com.apple.dock dashboard-in-overlay -bool true
  tags: osxdefaults

- name: Disable Dashboard
  command: defaults write com.apple.dashboard mcx-disabled -bool true
  tags: osxdefaults

- name: Make Terminal start faster
  command: touch {{ home }}/.hushlogin
  tags: osxdefaults

- name: Use all F1...F12 etc keys as standard functions
  command: defaults write NSGlobalDomain "com.apple.keyboard.fnState" -int 1
  tags: osxdefaults

- name: Fix Apple setup for zsh
  command: mv /etc/zshenv /etc/zprofile creates=/etc/zprofile
  sudo: yes
  tags: osxdefaults

- name: Enable Safari Develop mode
  command: defaults write com.apple.Safari IncludeDevelopMenu -bool true
  tags: osxdefaults

- name: Enable WebView Develop mode (all apps)
  command: defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
  when: 0 > 1
  tags: osxdefaults

- name: Disable Chrome swipe navigation
  command: defaults write com.google.Chrome.plist AppleEnableSwipeNavigateWithScrolls -bool FALSE
  tags: osxdefaults

# defaults write com.apple.Safari IncludeDevelopMenu -bool true &&
# defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true &&
# defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true &&
# defaults write NSGlobalDomain WebKitDeveloperExtras -bool true
